services:
  web-api:
    container_name: orderapp-main-api-web-api
    image: ${DOCKER_REGISTRY-}orderapp-main-api-web-api:v0.1.0
    build:
      context: .
      dockerfile: OrderApp.Main.Api.WebApi/Dockerfile
    depends_on: [ "default-db", "jobs-db" ]
  default-db:
    container_name: orderapp-main-api-default-db
    image: postgres:17
    volumes:
      - orderapp-main-api-default-db-data:/var/lib/postgresql/data
  jobs-db:
    container_name: orderapp-main-api-jobs-db
    image: postgres:17
    volumes:
      - orderapp-main-api-jobs-db-data:/var/lib/postgresql/data

volumes:
    orderapp-main-api-default-db-data:
    orderapp-main-api-jobs-db-data:
