services:
  web-api:
    container_name: orderapp-main-api-web-api
    image: ${DOCKER_REGISTRY-}orderapp-main-api-web-api:v0.1.0
    build:
      context: .
      dockerfile: OrderApp.Main.Api.WebApi/Dockerfile
    depends_on: ["default-db", "jobs", "opensearch"]
  jobs:
    container_name: orderapp-main-api-jobs
    image: ${DOCKER_REGISTRY-}orderapp-main-api-jobs:v0.1.0
    build:
      context: .
      dockerfile: OrderApp.Main.Api.Jobs/Dockerfile
    depends_on: ["default-db", "jobs-db"]   
  default-db:
    container_name: orderapp-main-api-default-db
    image: postgres:17
    volumes:
      - orderapp-main-api-default-db-data:/var/lib/postgresql/data
  jobs-db:
    container_name: orderapp-main-api-jobs-db
    image: postgres:17
    volumes:
      - orderapp-main-api-jobs-db-data:/var/lib/postgresql/data
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: orderapp-main-api-opensearch
    volumes:
      - orderapp-main-api-search-engine-data:/usr/share/opensearch/data
  opensearch-dashboard:
    container_name: orderapp-main-api-opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:3
    depends_on: ["opensearch"]

volumes:
    orderapp-main-api-default-db-data:
    orderapp-main-api-jobs-db-data:
    orderapp-main-api-search-engine-data:
