INSERT INTO "Products" ("Id", "Name", "ShortDescription", "Description", "Price") VALUES
(1, 'Wireless Mouse', 'Ergonomic wireless mouse', 'Comfortable wireless mouse with adjustable DPI and long battery life.', 25.99),
(2, 'Mechanical Keyboard', 'RGB mechanical keyboard', 'High-performance keyboard with customizable RGB lighting and tactile switches.', 79.99),
(3, 'HD Monitor', '24-inch Full HD monitor', 'Vibrant 24-inch monitor with HDMI and DisplayPort support.', 149.99),
(4, 'USB-C Hub', 'Multi-port USB-C hub', 'Compact hub with HDMI, USB 3.0, SD card reader, and power delivery.', 39.99),
(5, 'Noise Cancelling Headphones', 'Over-ear headphones', 'Premium headphones with active noise cancellation and 30-hour battery life.', 129.99),
(6, 'Webcam 1080p', 'Full HD webcam', '1080p webcam with autofocus and built-in microphone.', 49.99),
(7, 'Portable SSD', '1TB USB-C SSD', 'Fast and compact 1TB SSD with USB-C interface.', 109.99),
(8, 'Laptop Stand', 'Adjustable laptop stand', 'Aluminum stand with adjustable height and cooling design.', 29.99),
(9, 'Bluetooth Speaker', 'Portable speaker', 'Compact Bluetooth speaker with deep bass and 12-hour battery.', 59.99),
(10, 'Smartwatch', 'Fitness tracking smartwatch', 'Water-resistant smartwatch with heart rate monitor and GPS.', 199.99),
(11, 'Gaming Chair', 'Ergonomic gaming chair', 'Comfortable chair with lumbar support and adjustable armrests.', 249.99),
(12, 'Graphics Tablet', 'Drawing tablet with pen', 'Pressure-sensitive tablet for digital art and design.', 89.99),
(13, 'Wi-Fi Router', 'Dual-band Wi-Fi router', 'High-speed router with wide coverage and parental controls.', 99.99),
(14, 'External Hard Drive', '2TB USB 3.0 HDD', 'Reliable external hard drive for backups and storage.', 79.99),
(15, 'Smart Light Bulb', 'Wi-Fi LED bulb', 'Color-changing LED bulb controllable via app or voice.', 19.99),
(16, 'Action Camera', '4K waterproof camera', 'Compact action camera with 4K recording and waterproof case.', 139.99),
(17, 'Wireless Charger', 'Fast wireless charger', 'Qi-certified charger with fast charging support.', 34.99),
(18, 'Laptop Backpack', 'Water-resistant backpack', 'Spacious backpack with padded laptop compartment.', 44.99),
(19, 'Streaming Microphone', 'USB condenser mic', 'Professional-grade microphone for streaming and recording.', 89.99),
(20, 'VR Headset', 'Virtual reality headset', 'Immersive VR headset compatible with PC and console.', 299.99);

INSERT INTO "StockItems" ("Id", "ProductId", "Quantity") VALUES
(1, 1, 120),
(2, 2, 85),
(3, 3, 60),
(4, 4, 150),
(5, 5, 40),
(6, 6, 95),
(7, 7, 70),
(8, 8, 130),
(9, 9, 110),
(10, 10, 35),
(11, 11, 25),
(12, 12, 90),
(13, 13, 100),
(14, 14, 80),
(15, 15, 200),
(16, 16, 50),
(17, 17, 140),
(18, 18, 75),
(19, 19, 65),
(20, 20, 30);
