INSERT INTO "Products" ("Id", "Name", "ShortDescription", "Description", "Price") VALUES
(-1, 'Wireless Mouse', 'Ergonomic wireless mouse', 'A comfortable and responsive wireless mouse with long battery life.', 25.99),
(-2, 'Mechanical Keyboard', 'RGB mechanical keyboard', 'A high-quality mechanical keyboard with customizable RGB lighting.', 89.50),
(-3, 'USB-C Hub', 'Multi-port USB-C hub', 'Expand your laptop connectivity with this 6-in-1 USB-C hub.', 39.99),
(-4, 'Webcam', 'HD webcam', '1080p HD webcam with built-in microphone and privacy shutter.', 49.99),
(-5, 'Laptop Stand', 'Adjustable laptop stand', 'Ergonomic aluminum laptop stand with adjustable height and angle.', 34.95),
(-6, 'Bluetooth Speaker', 'Portable Bluetooth speaker', 'Compact speaker with powerful sound and long battery life.', 59.99),
(-7, 'External SSD', '1TB external SSD', 'High-speed portable solid-state drive with USB 3.1 interface.', 129.99),
(-8, 'Noise Cancelling Headphones', 'Over-ear headphones', 'Wireless headphones with active noise cancellation and long battery life.', 199.99),
(-9, 'Smartwatch', 'Fitness smartwatch', 'Water-resistant smartwatch with heart rate monitor and GPS.', 149.99),
(-10, 'Wireless Charger', 'Qi wireless charger', 'Fast wireless charging pad compatible with most smartphones.', 19.99),
(-11, 'Gaming Mouse Pad', 'RGB mouse pad', 'Large mouse pad with customizable RGB lighting.', 29.99),
(-12, 'Monitor Arm', 'Adjustable monitor arm', 'Gas spring monitor arm for ergonomic screen positioning.', 69.99),
(-13, 'Smart Light Bulb', 'Wi-Fi LED bulb', 'Color-changing LED bulb controllable via smartphone app.', 14.99),
(-14, 'Portable Monitor', '15.6-inch portable monitor', 'USB-C powered portable monitor for dual-screen productivity.', 179.99),
(-15, 'Ergonomic Chair', 'Mesh office chair', 'Adjustable ergonomic chair with lumbar support.', 249.99),
(-16, 'Graphic Tablet', 'Digital drawing tablet', 'Pressure-sensitive tablet for digital artists and designers.', 89.99),
(-17, 'Laptop Backpack', 'Water-resistant backpack', 'Spacious backpack with padded laptop compartment.', 54.99),
(-18, 'Smart Plug', 'Wi-Fi smart plug', 'Remote-controlled smart plug with energy monitoring.', 24.99),
(-19, 'Streaming Microphone', 'USB condenser mic', 'Professional-grade microphone for streaming and podcasting.', 99.99),
(-20, 'VR Headset', 'Virtual reality headset', 'Immersive VR headset compatible with PC and console.', 299.99);

-- Insert seed data into StockItems table
INSERT INTO "StockItems" ("Id", "ProductId", "Quantity") VALUES
(-1, -1, 150),
(-2, -2, 80),
(-3, -3, 200),
(-4, -4, 120),
(-5, -5, 90),
(-6, -6, 60),
(-7, -7, 75),
(-8, -8, 50),
(-9, -9, 110),
(-10, -10, 140),
(-11, -11, 160),
(-12, -12, 70),
(-13, -13, 130),
(-14, -14, 40),
(-15, -15, 30),
(-16, -16, 85),
(-17, -17, 95),
(-18, -18, 100),
(-19, -19, 55),
(-20, -20, 25);